### ISSUE TITLE
Not working on Peppermint10

### ISSUE THREAD

**Issue by MegDuck** [onuronsekiz/obamenu#2]
Hello. I'm trying to install your menu to my openbox10 ( Distribution Peppermint10 based on ubuntu 18.04)

Version of python - 3.6.9.

When i try to run python3 obamenu.py from terminal:
`
Traceback (most recent call last):
  File "obamenu.py", line 296, in <module>
    process_dtfile(dtf,  categoryDict)
  File "obamenu.py", line 247, in process_dtfile
    this.addIcon(eqi[1])				
  File "obamenu.py", line 133, in addIcon
    while tmp[0] != "/":
IndexError: list index out of range
`

python2 : 
`
Traceback (most recent call last):
  File "obamenu.py", line 275, in <module>
    addIconsToList(iconList, selected_theme) # getting first icons for list
  File "obamenu.py", line 65, in addIconsToList
    List.extend(tmp + "/" +  x for x in os.listdir(tmp) if x.lower().endswith(image_file_prefix))
OSError: [Errno 2] No such file or directory: '/var/lib/flatpak/exports/share//icons/ePepirus/48/legacy'
`

If i use it into openbox: Invalid output from pipe < my own path to your obamenu.py>.

I do chmod 754 obamenu.py

What I should do?

**Comment by onuronsekiz** [comment]
Python2 won't work with this code, no need to try with it.
Tried with peppermint10 livecd, issue is python2 is default selected. Make python3 as default.
Peppermint livecd (and probably your installation too) select default theme as hicolor, this is due to lack of gtkrc file.
To prevent this, change line 34 as _selected_theme = "gnome"_ or any other icon folder name in _/usr/share/icons_.
_selected_theme = "Adwaita"_ gives error too. It shouldn't and not giving on my setup but it gives error on peppermint.

Long word short, I think the problem on your setup is python version and default theme. Correct them and it will work.
